In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({
    'text': [
        'people watch campusx',
        'campusx watch campusx',
        'people write comment',
        'campusx write comment'
    ],
    'output': [1, 1, 0, 0]
})

In [3]:
df

,text,output
0,people watch campusx,1
1,campusx watch campusx,1
2,people write comment,0
3,campusx write comment,0


<h2>Bag of Words</h2>

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [5]:
bow=cv.fit_transform(df['text'])

In [7]:
#vocabulary
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [8]:
print(bow[0].toarray())

[[1 0 1 1 0]]


<p>people watch campusx
so as we can see the vocabulary index, campusx is 0, followed by comment,people,watch and write.

So for the first text, 
1,0,1,1,0 represents campusx, people and watch buffed</p>

In [9]:
print(bow[1].toarray())

[[2 0 0 1 0]]


<h3>Solves the OOV problem to some extent</h3>

In [10]:
cv.transform(["people watch campusx videos and comment on campusx videos"]).toarray()

array([[2, 1, 1, 1, 0]])

<p>Here even though the input has new vocabulary which werent present in the original dataframe, BoW ignores them and returns the freq array on the basis of the vocabulary words it is familiar with. Thus, it solves the Out Of Vocabulary (OOV) problem to an extent.

<b>However, the problem arises that it is completely ignoring the newly added words in the input thus the whole meaning of the sentence is ignored.</b></p>