In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({
    'text': [
        'people watch campusx',
        'campusx watch campusx',
        'people write comment',
        'campusx write comment'
    ],
    'output': [1, 1, 0, 0]
})

In [3]:
df

,text,output
0,people watch campusx,1
1,campusx watch campusx,1
2,people write comment,0
3,campusx write comment,0


<h2>n-grams</h2>

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(ngram_range=(2,2))

<h4>an ngram_range of (1, 1) means only unigrams, (1, 2) means unigrams and bigrams, and (2, 2) means only bigrams.</h4>

In [8]:
n_grams=cv.fit_transform(df['text'])

In [9]:
#vocabulary
print(cv.vocabulary_)

{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'people write': 3, 'write comment': 5, 'campusx write': 1}


In [11]:
print(n_grams[0].toarray())

[[0 0 1 0 1 0]]


In [12]:
print(n_grams[1].toarray())

[[1 0 0 0 1 0]]


In [13]:
print(n_grams.toarray())

[[0 0 1 0 1 0]
 [1 0 0 0 1 0]
 [0 0 0 1 0 1]
 [0 1 0 0 0 1]]
