In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({
    'text': [
        'people watch campusx',
        'campusx watch campusx',
        'people write comment',
        'campusx write comment'
    ],
    'output': [1, 1, 0, 0]
})

In [3]:
df

,text,output
0,people watch campusx,1
1,campusx watch campusx,1
2,people write comment,0
3,campusx write comment,0


<h2>Tf-Idf</h2>

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidfv=TfidfVectorizer()

In [6]:
tfidf=tfidfv.fit_transform(df['text'])

In [7]:
#vocabulary
print(tfidfv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [8]:
print(tfidf.toarray())

[[0.49681612 0.         0.61366674 0.61366674 0.        ]
 [0.8508161  0.         0.         0.52546357 0.        ]
 [0.         0.57735027 0.57735027 0.         0.57735027]
 [0.49681612 0.61366674 0.         0.         0.61366674]]


In [11]:
print(tfidfv.idf_)
print(tfidfv.get_feature_names_out())

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]
['campusx' 'comment' 'people' 'watch' 'write']
